version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  post_build:
    commands:
      - mvn clean package
      - mv target/vprofile-v2.war vprofile-v2.war
artifacts:
  files:
    - vprofile-v2.war
    - .ebextensions/**/*
  

