version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - npm install
      - apt-get update
      - apt-get install -y jq
      - wget http://www-eu.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz
      - tar xzf apache-maven-3.5.4-bin.tar.gz
      - ln -s apache-maven-3.5.4 maven    
  post_build:
    commands:
      - mvn package
      - mv target/vprofile-v2.war vprofile-v2.war
artifacts:
  files:
    - vprofile-v2.war
    - .ebextensions/**/*
  

